In [ ]:
import numpy as np

一、创建numpy数组（ndarray）

In [ ]:
## 1.基于列表或元组创建
a = np.array([1,2,3]) # 基于列表创建一维数组
b = np.array((1,2,3)) # 基于元组创建一维数组
c = np.array([[1,2,3],[4,5,6]],dtype=complex) # 基于列表创建二维数组，可指定数值类型

print(a,b,c)

In [ ]:
## 2.创建空数组
a = np.empty((3,4))

print(a)

In [ ]:
## 3.创建全1数组
a = np.ones([5,3],dtype=np.int)

print(a)

In [ ]:
## 4.创建全0数组
a = np.zeros([5,3],dtype=np.float)

print(a)

In [ ]:
## 5.创建全为指定数值的数组
a = np.full((3,5),6.6,float)

print(a)

In [ ]:
## 6.创建单位矩阵
a = np.eye(4)

print(a)

In [ ]:
## 7.创建对角矩阵
a = np.diag([5,6,7,8,9]) # 元素位于主对角线上
b = np.diag([5,6,7,8,9],2) # 元素位于主对角线上第2行

print(a,b)

In [ ]:
## 8.创建一维等差序列
a = range(4,10,2)
b = np.arange(4,10,2) # numpy的arange与python内建的range用法类似，但np.arange可生成浮点型序列，range只能生成整型序列

print(a,b)

In [ ]:
## 9.创建等差数列、等比数列
a = np.linspace(3,9,5) #等差数列，起始为3，终止为9，个数为5
b = np.logspace(2,6,5,base=2) #等比数列，起始为2，终止为6，个数为5，底为2

print(a,b)

In [ ]:
## 10.根据行号、列号生成相应位置的矩阵元素
def func(i,j):
    return i+j

a = np.fromfunction(func,(5,6))

print(a)

In [ ]:
## 11.生成随机数组

# 随机浮点型数组，范围(0,1)
a = np.random.rand(3,5)

print('浮点型数组\n',a)

# 随机整型数组，可指定范围
a = np.random.randint(0,100,size=3) # [0,100)范围内的形状为3的一维数组
b = np.random.randint(0,100,size=(3,4)) # [0,100)范围内的形状 为(3,4)的二维数组

print('整型数组\n',a,b)

# 均匀分布数组
a = np.random.uniform(1,5,10) #[1,5)范围内的形状为10的一维数组
b = np.random.uniform(1,5,(3,4)) #[1,5)范围内的形状 为(3,4)的二维数组

print('均匀分布数组\n',a,b)

# 正态分布数组
a = np.random.normal(loc=1.75,scale=0.1,size=[4,5]) #4行5列的二维数组

print('正态分布数组\n',a)

二、查看numpy数组的属性

In [ ]:
## 1.数组形状：shape
a = np.array([[1,2,3],[4,5,6]])

print(a.shape,a.shape[0],a.shape[1])

In [ ]:
## 2.数组维度：ndim
a = np.array([[1,2,3],[4,5,6]])

print(a.ndim)

In [ ]:
## 3.数组元素个数：size
a = np.array([[1,2,3],[4,5,6]])

print(a.size)

In [ ]:
## 4.数组元素的类型：dtype
a = np.array([[1,2,3],[4,5,6]])

print(a.dtype)

三、numpy数组元素的截取

In [ ]:
## 1.按行列截取
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(a[0:1]) #截取第一行,返回 [[1 2 3 4 5]]
print(a[1,2:5]) #截取第二行，第三、四、五列，返回 [8 9 10]
print(a[1,:]) #截取第二行,返回 [ 6  7  8  9 10]

In [25]:
## 2.按条件（布尔表达式）截取
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = a[a>6] # 截取矩阵a中大于6的元素，返回的是一维数组（[7,8,9,10]]）

print(b)

# 注：numpy数组与数值的关系运算，结果还是个数组
print(a>6)

[ 7  8  9 10]
[[False False False False False]
 [False  True  True  True  True]]


In [28]:
## 3.按条件处理数组
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

# (1) 对按条件截取的元素重新赋值
a[a>6] = 0
print(a)

# (2) 按条件将数组元素分为两部分，分别赋一个值：np.where
b = np.where(a==0,1,-1)
print(b)

[[1 2 3 4 5]
 [6 0 0 0 0]]
[[-1 -1 -1 -1 -1]
 [-1  1  1  1  1]]


四、numpy数组合并

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print('a:\n',a)
print('b:\n',b)

In [ ]:
## 竖着合并
print(np.vstack((a,b)))

In [ ]:
## 横着合并
print(np.hstack((a,b)))

五、numpy数组常用方法

In [ ]:
## 1.数组复制
a = np.array([[1,2,3,4,5],[6,7,8,9,0]])
b = np.copy(a[:,2:5]) #将数组a的第2-5列拷贝成数组b

print(b)

In [ ]:
## 2.数组排序
a = np.array([[2.5,3,0.6],[11,10.5,10.1],[5,21,6]])

print('a\n',a)
print('行排序\n',np.sort(a,axis=0)) # 行排序
print('列排序\n',np.sort(a,axis=1)) # 列排序

In [ ]:
## 3.数组去重
a = np.array([[1,2,3,3],[2,5,5,6]])

print(np.unique(a)) # 返回一个一维数组

In [ ]:
## 4.数组转置
a = np.array([[1,2,3],[4,5,6]])

print(a.T)

In [ ]:
## 5.改变数组的形状：reshape或resize
a = np.random.randint(1,100,12)
print('a.shape =\n',a.shape)

# reshape，注意元素个数不能改变
b = a.reshape(3,4) # 指定维数
print('b =\n',b)

c = a.reshape(-1,2)
print('c =\n',c)

# resize，元素个数可以改变
d = np.random.randint(1,100,(3,3,5))
print('d.shape =\n',d.shape)

d.resize(10,5) # 若元素个数增多，则多出来的部分用0填充
print('d = \n',d)

注意：  
reshape与resize的区别：  
第一，reshape()函数改变数组形状，但元素个数不能变；resize()函数改变数组形状，元素个数可以变（多出来的部分充0）。  
第二，reshape()函数产生新的数组，原数组不变；resize()函数在原数组上修改。